// This file is automatically generated. DO NOT EDIT.

package bfrest

type BESAPI struct {
	Action []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Action"`
}
