// This file is automatically generated. DO NOT EDIT.

package bfrest

type BES struct {
	ActionSite *struct {
		Description          struct{} `xml:"Description"`
		DisplayName          string   `xml:"DisplayName"`
		GatherURL            string   `xml:"GatherURL"`
		GlobalReadPermission bool     `xml:"GlobalReadPermission"`
		Name                 string   `xml:"Name"`
		Subscription         struct {
			Mode string `xml:"Mode"`
		} `xml:"Subscription"`
	} `xml:"ActionSite"`
	Analysis *struct {
		CVENames    *struct{} `xml:"CVENames"`
		Category    *string   `xml:"Category"`
		Delay       *string   `xml:"Delay"`
		Description string    `xml:"Description"`
		Domain      *string   `xml:"Domain"`
		MIMEField   []struct {
			Name  string `xml:"Name"`
			Value string `xml:"Value"`
		} `xml:"MIMEField"`
		Property []struct {
			EvaluationPeriod *string `xml:"EvaluationPeriod,attr"`
			ID               int     `xml:"ID,attr"`
			Name             string  `xml:"Name,attr"`
			CharData         string  `xml:",chardata"`
		} `xml:"Property"`
		Relevance         []string `xml:"Relevance"`
		Source            *string  `xml:"Source"`
		SourceID          *string  `xml:"SourceID"`
		SourceReleaseDate *string  `xml:"SourceReleaseDate"`
		SourceSeverity    *string  `xml:"SourceSeverity"`
		Title             string   `xml:"Title"`
	} `xml:"Analysis"`
	Baseline *struct {
		BaselineComponentCollection struct {
			BaselineComponentGroup struct {
				BaselineComponent []struct {
					ActionName         string `xml:"ActionName,attr"`
					IncludeInRelevance bool   `xml:"IncludeInRelevance,attr"`
					Name               string `xml:"Name,attr"`
					SourceID           int    `xml:"SourceID,attr"`
					SourceSiteURL      string `xml:"SourceSiteURL,attr"`
					SyncStatus         string `xml:"SyncStatus,attr"`
					ActionScript       struct {
						MIMEType string `xml:"MIMEType,attr"`
						CharData string `xml:",chardata"`
					} `xml:"ActionScript"`
					Relevance       string `xml:"Relevance"`
					SuccessCriteria struct {
						Option string `xml:"Option,attr"`
					} `xml:"SuccessCriteria"`
				} `xml:"BaselineComponent"`
			} `xml:"BaselineComponentGroup"`
		} `xml:"BaselineComponentCollection"`
		CVENames    struct{} `xml:"CVENames"`
		Category    struct{} `xml:"Category"`
		Description string   `xml:"Description"`
		Domain      string   `xml:"Domain"`
		MIMEField   struct {
			Name  string `xml:"Name"`
			Value string `xml:"Value"`
		} `xml:"MIMEField"`
		Relevance      bool     `xml:"Relevance"`
		SANSID         struct{} `xml:"SANSID"`
		Source         struct{} `xml:"Source"`
		SourceID       struct{} `xml:"SourceID"`
		SourceSeverity struct{} `xml:"SourceSeverity"`
		Title          string   `xml:"Title"`
	} `xml:"Baseline"`
	ComputerGroup *struct {
		Domain                           string `xml:"Domain"`
		JoinByIntersection               bool   `xml:"JoinByIntersection"`
		SearchComponentPropertyReference *struct {
			Comparison   string `xml:"Comparison,attr"`
			PropertyName string `xml:"PropertyName,attr"`
			Relevance    string `xml:"Relevance"`
			SearchText   string `xml:"SearchText"`
		} `xml:"SearchComponentPropertyReference"`
		SearchComponentRelevance *struct {
			Comparison string `xml:"Comparison,attr"`
			Relevance  string `xml:"Relevance"`
		} `xml:"SearchComponentRelevance"`
		Title string `xml:"Title"`
	} `xml:"ComputerGroup"`
	CustomSite *struct {
		Description          struct{} `xml:"Description"`
		DisplayName          string   `xml:"DisplayName"`
		Domain               string   `xml:"Domain"`
		GatherURL            string   `xml:"GatherURL"`
		GlobalReadPermission bool     `xml:"GlobalReadPermission"`
		Name                 string   `xml:"Name"`
		Subscription         struct {
			CustomGroup *struct {
				JoinByIntersection               bool `xml:"JoinByIntersection,attr"`
				SearchComponentPropertyReference struct {
					Comparison   string `xml:"Comparison,attr"`
					PropertyName string `xml:"PropertyName,attr"`
					Relevance    string `xml:"Relevance"`
					SearchText   string `xml:"SearchText"`
				} `xml:"SearchComponentPropertyReference"`
			} `xml:"CustomGroup"`
			Mode string `xml:"Mode"`
		} `xml:"Subscription"`
	} `xml:"CustomSite"`
	ExternalSite *struct {
		Description          struct{} `xml:"Description"`
		DisplayName          string   `xml:"DisplayName"`
		GatherURL            string   `xml:"GatherURL"`
		GlobalReadPermission bool     `xml:"GlobalReadPermission"`
		Name                 string   `xml:"Name"`
		Subscription         struct {
			CustomGroup struct {
				JoinByIntersection       bool `xml:"JoinByIntersection,attr"`
				SearchComponentRelevance struct {
					Comparison string `xml:"Comparison,attr"`
					Relevance  string `xml:"Relevance"`
				} `xml:"SearchComponentRelevance"`
			} `xml:"CustomGroup"`
			Mode string `xml:"Mode"`
		} `xml:"Subscription"`
	} `xml:"ExternalSite"`
	Fixlet *struct {
		Action []struct {
			ID           string `xml:"ID,attr"`
			ActionScript struct {
				MIMEType string `xml:"MIMEType,attr"`
				CharData string `xml:",chardata"`
			} `xml:"ActionScript"`
			Description struct {
				Link     string `xml:"Link"`
				PostLink string `xml:"PostLink"`
				PreLink  string `xml:"PreLink"`
			} `xml:"Description"`
			Settings *struct {
				ActiveUserRequirement   string `xml:"ActiveUserRequirement"`
				ActiveUserType          string `xml:"ActiveUserType"`
				ContinueOnErrors        bool   `xml:"ContinueOnErrors"`
				EndDateTimeLocalOffset  string `xml:"EndDateTimeLocalOffset"`
				HasDayOfWeekConstraint  bool   `xml:"HasDayOfWeekConstraint"`
				HasEndTime              bool   `xml:"HasEndTime"`
				HasReapplyInterval      bool   `xml:"HasReapplyInterval"`
				HasReapplyLimit         bool   `xml:"HasReapplyLimit"`
				HasRetry                bool   `xml:"HasRetry"`
				HasRunningMessage       bool   `xml:"HasRunningMessage"`
				HasStartTime            bool   `xml:"HasStartTime"`
				HasTemporalDistribution bool   `xml:"HasTemporalDistribution"`
				HasTimeRange            bool   `xml:"HasTimeRange"`
				HasWhose                bool   `xml:"HasWhose"`
				IsOffer                 bool   `xml:"IsOffer"`
				PostActionBehavior      struct {
					Behavior                   string `xml:"Behavior,attr"`
					AllowCancel                bool   `xml:"AllowCancel"`
					PostActionDeadlineBehavior string `xml:"PostActionDeadlineBehavior"`
					PostActionDeadlineInterval string `xml:"PostActionDeadlineInterval"`
				} `xml:"PostActionBehavior"`
				PreActionCacheDownload bool `xml:"PreActionCacheDownload"`
				PreActionShowUI        bool `xml:"PreActionShowUI"`
				Reapply                bool `xml:"Reapply"`
				ReapplyLimit           int  `xml:"ReapplyLimit"`
				UseUTCTime             bool `xml:"UseUTCTime"`
			} `xml:"Settings"`
			SettingsLocks *struct {
				ActionUITitle         bool `xml:"ActionUITitle"`
				ActiveUserRequirement bool `xml:"ActiveUserRequirement"`
				ActiveUserType        bool `xml:"ActiveUserType"`
				AnnounceOffer         bool `xml:"AnnounceOffer"`
				ContinueOnErrors      bool `xml:"ContinueOnErrors"`
				DayOfWeekConstraint   bool `xml:"DayOfWeekConstraint"`
				EndDateTimeOffset     bool `xml:"EndDateTimeOffset"`
				HasRunningMessage     bool `xml:"HasRunningMessage"`
				IsOffer               bool `xml:"IsOffer"`
				OfferCategory         bool `xml:"OfferCategory"`
				OfferDescriptionHTML  bool `xml:"OfferDescriptionHTML"`
				PostActionBehavior    struct {
					AllowCancel bool `xml:"AllowCancel"`
					Behavior    bool `xml:"Behavior"`
					Deadline    bool `xml:"Deadline"`
					Text        bool `xml:"Text"`
					Title       bool `xml:"Title"`
				} `xml:"PostActionBehavior"`
				PreAction struct {
					AskToSaveWork    bool `xml:"AskToSaveWork"`
					DeadlineBehavior bool `xml:"DeadlineBehavior"`
					ShowActionButton bool `xml:"ShowActionButton"`
					ShowCancelButton bool `xml:"ShowCancelButton"`
					ShowConfirmation bool `xml:"ShowConfirmation"`
					Text             bool `xml:"Text"`
				} `xml:"PreAction"`
				PreActionCacheDownload bool `xml:"PreActionCacheDownload"`
				PreActionShowUI        bool `xml:"PreActionShowUI"`
				Reapply                bool `xml:"Reapply"`
				ReapplyLimit           bool `xml:"ReapplyLimit"`
				RetryCount             bool `xml:"RetryCount"`
				RetryWait              bool `xml:"RetryWait"`
				RunningMessage         struct {
					Text bool `xml:"Text"`
				} `xml:"RunningMessage"`
				StartDateTimeOffset  bool `xml:"StartDateTimeOffset"`
				TemporalDistribution bool `xml:"TemporalDistribution"`
				TimeRange            bool `xml:"TimeRange"`
				Whose                bool `xml:"Whose"`
			} `xml:"SettingsLocks"`
			SuccessCriteria *struct {
				Option   string `xml:"Option,attr"`
				CharData string `xml:",chardata"`
			} `xml:"SuccessCriteria"`
		} `xml:"Action"`
		CVENames      *string `xml:"CVENames"`
		Category      *string `xml:"Category"`
		DefaultAction *struct {
			ID           string `xml:"ID,attr"`
			ActionScript struct {
				MIMEType string `xml:"MIMEType,attr"`
				CharData string `xml:",chardata"`
			} `xml:"ActionScript"`
			Description struct {
				Link     string `xml:"Link"`
				PostLink string `xml:"PostLink"`
				PreLink  string `xml:"PreLink"`
			} `xml:"Description"`
			Settings *struct {
				ActiveUserRequirement   string `xml:"ActiveUserRequirement"`
				ActiveUserType          string `xml:"ActiveUserType"`
				ContinueOnErrors        bool   `xml:"ContinueOnErrors"`
				HasDayOfWeekConstraint  bool   `xml:"HasDayOfWeekConstraint"`
				HasEndTime              bool   `xml:"HasEndTime"`
				HasReapplyInterval      bool   `xml:"HasReapplyInterval"`
				HasReapplyLimit         bool   `xml:"HasReapplyLimit"`
				HasRetry                bool   `xml:"HasRetry"`
				HasRunningMessage       bool   `xml:"HasRunningMessage"`
				HasStartTime            bool   `xml:"HasStartTime"`
				HasTemporalDistribution bool   `xml:"HasTemporalDistribution"`
				HasTimeRange            bool   `xml:"HasTimeRange"`
				HasWhose                bool   `xml:"HasWhose"`
				IsOffer                 bool   `xml:"IsOffer"`
				PostActionBehavior      struct {
					Behavior string `xml:"Behavior,attr"`
				} `xml:"PostActionBehavior"`
				PreActionCacheDownload bool   `xml:"PreActionCacheDownload"`
				PreActionShowUI        bool   `xml:"PreActionShowUI"`
				Reapply                bool   `xml:"Reapply"`
				ReapplyInterval        string `xml:"ReapplyInterval"`
				UseUTCTime             bool   `xml:"UseUTCTime"`
			} `xml:"Settings"`
			SettingsLocks *struct {
				ActionUITitle         bool `xml:"ActionUITitle"`
				ActiveUserRequirement bool `xml:"ActiveUserRequirement"`
				ActiveUserType        bool `xml:"ActiveUserType"`
				AnnounceOffer         bool `xml:"AnnounceOffer"`
				ContinueOnErrors      bool `xml:"ContinueOnErrors"`
				DayOfWeekConstraint   bool `xml:"DayOfWeekConstraint"`
				EndDateTimeOffset     bool `xml:"EndDateTimeOffset"`
				HasRunningMessage     bool `xml:"HasRunningMessage"`
				IsOffer               bool `xml:"IsOffer"`
				OfferCategory         bool `xml:"OfferCategory"`
				OfferDescriptionHTML  bool `xml:"OfferDescriptionHTML"`
				PostActionBehavior    struct {
					AllowCancel bool `xml:"AllowCancel"`
					Behavior    bool `xml:"Behavior"`
					Deadline    bool `xml:"Deadline"`
					Text        bool `xml:"Text"`
					Title       bool `xml:"Title"`
				} `xml:"PostActionBehavior"`
				PreAction struct {
					AskToSaveWork    bool `xml:"AskToSaveWork"`
					DeadlineBehavior bool `xml:"DeadlineBehavior"`
					ShowActionButton bool `xml:"ShowActionButton"`
					ShowCancelButton bool `xml:"ShowCancelButton"`
					ShowConfirmation bool `xml:"ShowConfirmation"`
					Text             bool `xml:"Text"`
				} `xml:"PreAction"`
				PreActionCacheDownload bool `xml:"PreActionCacheDownload"`
				PreActionShowUI        bool `xml:"PreActionShowUI"`
				Reapply                bool `xml:"Reapply"`
				ReapplyLimit           bool `xml:"ReapplyLimit"`
				RetryCount             bool `xml:"RetryCount"`
				RetryWait              bool `xml:"RetryWait"`
				RunningMessage         struct {
					Text bool `xml:"Text"`
				} `xml:"RunningMessage"`
				StartDateTimeOffset  bool `xml:"StartDateTimeOffset"`
				TemporalDistribution bool `xml:"TemporalDistribution"`
				TimeRange            bool `xml:"TimeRange"`
				Whose                bool `xml:"Whose"`
			} `xml:"SettingsLocks"`
			SuccessCriteria *struct {
				Option   string `xml:"Option,attr"`
				CharData string `xml:",chardata"`
			} `xml:"SuccessCriteria"`
		} `xml:"DefaultAction"`
		Delay          *string `xml:"Delay"`
		Description    string  `xml:"Description"`
		Domain         *string `xml:"Domain"`
		DownloadSize   *int    `xml:"DownloadSize"`
		GroupRelevance *struct {
			JoinByIntersection       bool `xml:"JoinByIntersection,attr"`
			SearchComponentRelevance struct {
				Comparison string `xml:"Comparison,attr"`
				Relevance  string `xml:"Relevance"`
			} `xml:"SearchComponentRelevance"`
		} `xml:"GroupRelevance"`
		MIMEField []struct {
			Name  string `xml:"Name"`
			Value string `xml:"Value"`
		} `xml:"MIMEField"`
		Relevance         []string `xml:"Relevance"`
		SANSID            *string  `xml:"SANSID"`
		Source            string   `xml:"Source"`
		SourceID          string   `xml:"SourceID"`
		SourceReleaseDate *string  `xml:"SourceReleaseDate"`
		SourceSeverity    *string  `xml:"SourceSeverity"`
		Title             string   `xml:"Title"`
	} `xml:"Fixlet"`
	MultipleActionGroup *struct {
		MemberAction []struct {
			ActionScript struct {
				MIMEType string `xml:"MIMEType,attr"`
				CharData string `xml:",chardata"`
			} `xml:"ActionScript"`
			IncludeInGroupRelevance bool   `xml:"IncludeInGroupRelevance"`
			Relevance               string `xml:"Relevance"`
			SuccessCriteria         struct {
				Option string `xml:"Option,attr"`
			} `xml:"SuccessCriteria"`
			Title string `xml:"Title"`
		} `xml:"MemberAction"`
		Relevance bool `xml:"Relevance"`
		Settings  struct {
			ActiveUserRequirement   string `xml:"ActiveUserRequirement"`
			ActiveUserType          string `xml:"ActiveUserType"`
			ContinueOnErrors        bool   `xml:"ContinueOnErrors"`
			EndDateTimeLocalOffset  string `xml:"EndDateTimeLocalOffset"`
			HasDayOfWeekConstraint  bool   `xml:"HasDayOfWeekConstraint"`
			HasEndTime              bool   `xml:"HasEndTime"`
			HasReapplyInterval      bool   `xml:"HasReapplyInterval"`
			HasReapplyLimit         bool   `xml:"HasReapplyLimit"`
			HasRetry                bool   `xml:"HasRetry"`
			HasRunningMessage       bool   `xml:"HasRunningMessage"`
			HasStartTime            bool   `xml:"HasStartTime"`
			HasTemporalDistribution bool   `xml:"HasTemporalDistribution"`
			HasTimeRange            bool   `xml:"HasTimeRange"`
			HasWhose                bool   `xml:"HasWhose"`
			IsOffer                 bool   `xml:"IsOffer"`
			PostActionBehavior      struct {
				Behavior string `xml:"Behavior,attr"`
			} `xml:"PostActionBehavior"`
			PreActionCacheDownload bool `xml:"PreActionCacheDownload"`
			PreActionShowUI        bool `xml:"PreActionShowUI"`
			Reapply                bool `xml:"Reapply"`
			ReapplyLimit           int  `xml:"ReapplyLimit"`
			UseUTCTime             bool `xml:"UseUTCTime"`
		} `xml:"Settings"`
		SettingsLocks struct {
			ActionUITitle         bool `xml:"ActionUITitle"`
			ActiveUserRequirement bool `xml:"ActiveUserRequirement"`
			ActiveUserType        bool `xml:"ActiveUserType"`
			AnnounceOffer         bool `xml:"AnnounceOffer"`
			ContinueOnErrors      bool `xml:"ContinueOnErrors"`
			DayOfWeekConstraint   bool `xml:"DayOfWeekConstraint"`
			EndDateTimeOffset     bool `xml:"EndDateTimeOffset"`
			HasRunningMessage     bool `xml:"HasRunningMessage"`
			IsOffer               bool `xml:"IsOffer"`
			OfferCategory         bool `xml:"OfferCategory"`
			OfferDescriptionHTML  bool `xml:"OfferDescriptionHTML"`
			PostActionBehavior    struct {
				AllowCancel bool `xml:"AllowCancel"`
				Behavior    bool `xml:"Behavior"`
				Deadline    bool `xml:"Deadline"`
				Text        bool `xml:"Text"`
				Title       bool `xml:"Title"`
			} `xml:"PostActionBehavior"`
			PreAction struct {
				AskToSaveWork    bool `xml:"AskToSaveWork"`
				DeadlineBehavior bool `xml:"DeadlineBehavior"`
				ShowActionButton bool `xml:"ShowActionButton"`
				ShowCancelButton bool `xml:"ShowCancelButton"`
				ShowConfirmation bool `xml:"ShowConfirmation"`
				Text             bool `xml:"Text"`
			} `xml:"PreAction"`
			PreActionCacheDownload bool `xml:"PreActionCacheDownload"`
			PreActionShowUI        bool `xml:"PreActionShowUI"`
			Reapply                bool `xml:"Reapply"`
			ReapplyLimit           bool `xml:"ReapplyLimit"`
			RetryCount             bool `xml:"RetryCount"`
			RetryWait              bool `xml:"RetryWait"`
			RunningMessage         struct {
				Text bool `xml:"Text"`
			} `xml:"RunningMessage"`
			StartDateTimeOffset  bool `xml:"StartDateTimeOffset"`
			TemporalDistribution bool `xml:"TemporalDistribution"`
			TimeRange            bool `xml:"TimeRange"`
			Whose                bool `xml:"Whose"`
		} `xml:"SettingsLocks"`
		Target struct {
			ComputerID      *int    `xml:"ComputerID"`
			CustomRelevance *string `xml:"CustomRelevance"`
		} `xml:"Target"`
		Title string `xml:"Title"`
	} `xml:"MultipleActionGroup"`
	OperatorSite *struct {
		DisplayName string `xml:"DisplayName"`
		GatherURL   string `xml:"GatherURL"`
		Name        string `xml:"Name"`
	} `xml:"OperatorSite"`
	Property *struct {
		EvaluationPeriod *string `xml:"EvaluationPeriod,attr"`
		Name             string  `xml:"Name,attr"`
		CharData         string  `xml:",chardata"`
	} `xml:"Property"`
	SingleAction *struct {
		ActionScript struct {
			MIMEType string `xml:"MIMEType,attr"`
			CharData string `xml:",chardata"`
		} `xml:"ActionScript"`
		IsUrgent  bool `xml:"IsUrgent"`
		Parameter []struct {
			Name     string `xml:"Name,attr"`
			CharData string `xml:",chardata"`
		} `xml:"Parameter"`
		Relevance string `xml:"Relevance"`
		Settings  struct {
			ActionUITitle           *string `xml:"ActionUITitle"`
			ActiveUserRequirement   string  `xml:"ActiveUserRequirement"`
			ActiveUserType          string  `xml:"ActiveUserType"`
			ContinueOnErrors        bool    `xml:"ContinueOnErrors"`
			EndDateTimeLocalOffset  *string `xml:"EndDateTimeLocalOffset"`
			HasDayOfWeekConstraint  bool    `xml:"HasDayOfWeekConstraint"`
			HasEndTime              bool    `xml:"HasEndTime"`
			HasReapplyInterval      bool    `xml:"HasReapplyInterval"`
			HasReapplyLimit         bool    `xml:"HasReapplyLimit"`
			HasRetry                bool    `xml:"HasRetry"`
			HasRunningMessage       bool    `xml:"HasRunningMessage"`
			HasStartTime            bool    `xml:"HasStartTime"`
			HasTemporalDistribution bool    `xml:"HasTemporalDistribution"`
			HasTimeRange            bool    `xml:"HasTimeRange"`
			HasWhose                bool    `xml:"HasWhose"`
			IsOffer                 bool    `xml:"IsOffer"`
			PostActionBehavior      struct {
				Behavior                   string  `xml:"Behavior,attr"`
				AllowCancel                *bool   `xml:"AllowCancel"`
				PostActionDeadlineBehavior *string `xml:"PostActionDeadlineBehavior"`
				PostActionDeadlineInterval *string `xml:"PostActionDeadlineInterval"`
				Text                       *string `xml:"Text"`
				Title                      *string `xml:"Title"`
			} `xml:"PostActionBehavior"`
			PreAction *struct {
				AskToSaveWork    bool   `xml:"AskToSaveWork"`
				DeadlineBehavior string `xml:"DeadlineBehavior"`
				DeadlineInterval string `xml:"DeadlineInterval"`
				DeadlineType     string `xml:"DeadlineType"`
				ShowActionButton bool   `xml:"ShowActionButton"`
				ShowCancelButton bool   `xml:"ShowCancelButton"`
				ShowConfirmation bool   `xml:"ShowConfirmation"`
				Text             string `xml:"Text"`
			} `xml:"PreAction"`
			PreActionCacheDownload bool    `xml:"PreActionCacheDownload"`
			PreActionShowUI        bool    `xml:"PreActionShowUI"`
			Reapply                bool    `xml:"Reapply"`
			ReapplyInterval        *string `xml:"ReapplyInterval"`
			ReapplyLimit           *int    `xml:"ReapplyLimit"`
			RetryCount             *int    `xml:"RetryCount"`
			RetryWait              *struct {
				Behavior string `xml:"Behavior,attr"`
				CharData string `xml:",chardata"`
			} `xml:"RetryWait"`
			StartDateTimeLocalOffset *string `xml:"StartDateTimeLocalOffset"`
			TemporalDistribution     *string `xml:"TemporalDistribution"`
			TimeRange                *struct {
				EndTime   string `xml:"EndTime"`
				StartTime string `xml:"StartTime"`
			} `xml:"TimeRange"`
			UseUTCTime bool `xml:"UseUTCTime"`
		} `xml:"Settings"`
		SettingsLocks struct {
			ActionUITitle         bool `xml:"ActionUITitle"`
			ActiveUserRequirement bool `xml:"ActiveUserRequirement"`
			ActiveUserType        bool `xml:"ActiveUserType"`
			AnnounceOffer         bool `xml:"AnnounceOffer"`
			ContinueOnErrors      bool `xml:"ContinueOnErrors"`
			DayOfWeekConstraint   bool `xml:"DayOfWeekConstraint"`
			EndDateTimeOffset     bool `xml:"EndDateTimeOffset"`
			HasRunningMessage     bool `xml:"HasRunningMessage"`
			IsOffer               bool `xml:"IsOffer"`
			OfferCategory         bool `xml:"OfferCategory"`
			OfferDescriptionHTML  bool `xml:"OfferDescriptionHTML"`
			PostActionBehavior    struct {
				AllowCancel bool `xml:"AllowCancel"`
				Behavior    bool `xml:"Behavior"`
				Deadline    bool `xml:"Deadline"`
				Text        bool `xml:"Text"`
				Title       bool `xml:"Title"`
			} `xml:"PostActionBehavior"`
			PreAction struct {
				AskToSaveWork    bool `xml:"AskToSaveWork"`
				DeadlineBehavior bool `xml:"DeadlineBehavior"`
				ShowActionButton bool `xml:"ShowActionButton"`
				ShowCancelButton bool `xml:"ShowCancelButton"`
				ShowConfirmation bool `xml:"ShowConfirmation"`
				Text             bool `xml:"Text"`
			} `xml:"PreAction"`
			PreActionCacheDownload bool `xml:"PreActionCacheDownload"`
			PreActionShowUI        bool `xml:"PreActionShowUI"`
			Reapply                bool `xml:"Reapply"`
			ReapplyLimit           bool `xml:"ReapplyLimit"`
			RetryCount             bool `xml:"RetryCount"`
			RetryWait              bool `xml:"RetryWait"`
			RunningMessage         struct {
				Text bool `xml:"Text"`
			} `xml:"RunningMessage"`
			StartDateTimeOffset  bool `xml:"StartDateTimeOffset"`
			TemporalDistribution bool `xml:"TemporalDistribution"`
			TimeRange            bool `xml:"TimeRange"`
			Whose                bool `xml:"Whose"`
		} `xml:"SettingsLocks"`
		SuccessCriteria struct {
			Option   string `xml:"Option,attr"`
			CharData string `xml:",chardata"`
		} `xml:"SuccessCriteria"`
		Target struct {
			AllComputers    *int    `xml:"AllComputers"`
			ComputerID      []int   `xml:"ComputerID"`
			CustomRelevance *string `xml:"CustomRelevance"`
		} `xml:"Target"`
		Title string `xml:"Title"`
	} `xml:"SingleAction"`
	Task struct {
		Action []struct {
			ID           string `xml:"ID,attr"`
			ActionScript struct {
				MIMEType string `xml:"MIMEType,attr"`
				CharData string `xml:",chardata"`
			} `xml:"ActionScript"`
			Description struct {
				Link     string `xml:"Link"`
				PostLink string `xml:"PostLink"`
				PreLink  string `xml:"PreLink"`
			} `xml:"Description"`
			SuccessCriteria *struct {
				Option   string `xml:"Option,attr"`
				CharData string `xml:",chardata"`
			} `xml:"SuccessCriteria"`
		} `xml:"Action"`
		CVENames      *string `xml:"CVENames"`
		Category      string  `xml:"Category"`
		DefaultAction *struct {
			ID           string `xml:"ID,attr"`
			ActionScript struct {
				MIMEType string `xml:"MIMEType,attr"`
				CharData string `xml:",chardata"`
			} `xml:"ActionScript"`
			Description struct {
				Link     string `xml:"Link"`
				PostLink string `xml:"PostLink"`
				PreLink  string `xml:"PreLink"`
			} `xml:"Description"`
			Settings *struct {
				ActiveUserRequirement   string `xml:"ActiveUserRequirement"`
				ActiveUserType          string `xml:"ActiveUserType"`
				ContinueOnErrors        bool   `xml:"ContinueOnErrors"`
				HasDayOfWeekConstraint  bool   `xml:"HasDayOfWeekConstraint"`
				HasEndTime              bool   `xml:"HasEndTime"`
				HasReapplyInterval      bool   `xml:"HasReapplyInterval"`
				HasReapplyLimit         bool   `xml:"HasReapplyLimit"`
				HasRetry                bool   `xml:"HasRetry"`
				HasRunningMessage       bool   `xml:"HasRunningMessage"`
				HasStartTime            bool   `xml:"HasStartTime"`
				HasTemporalDistribution bool   `xml:"HasTemporalDistribution"`
				HasTimeRange            bool   `xml:"HasTimeRange"`
				HasWhose                bool   `xml:"HasWhose"`
				IsOffer                 bool   `xml:"IsOffer"`
				PostActionBehavior      struct {
					Behavior string `xml:"Behavior,attr"`
				} `xml:"PostActionBehavior"`
				PreActionCacheDownload bool `xml:"PreActionCacheDownload"`
				PreActionShowUI        bool `xml:"PreActionShowUI"`
				Reapply                bool `xml:"Reapply"`
				RetryCount             int  `xml:"RetryCount"`
				RetryWait              struct {
					Behavior string `xml:"Behavior,attr"`
					CharData string `xml:",chardata"`
				} `xml:"RetryWait"`
				UseUTCTime bool `xml:"UseUTCTime"`
			} `xml:"Settings"`
			SuccessCriteria *struct {
				Option   string `xml:"Option,attr"`
				CharData string `xml:",chardata"`
			} `xml:"SuccessCriteria"`
		} `xml:"DefaultAction"`
		Delay        *string `xml:"Delay"`
		Description  string  `xml:"Description"`
		Domain       *string `xml:"Domain"`
		DownloadSize *int    `xml:"DownloadSize"`
		MIMEField    []struct {
			Name  string `xml:"Name"`
			Value string `xml:"Value"`
		} `xml:"MIMEField"`
		Relevance         []string `xml:"Relevance"`
		SANSID            *string  `xml:"SANSID"`
		Source            string   `xml:"Source"`
		SourceID          string   `xml:"SourceID"`
		SourceReleaseDate *string  `xml:"SourceReleaseDate"`
		SourceSeverity    string   `xml:"SourceSeverity"`
		Title             string   `xml:"Title"`
	} `xml:"Task"`
}

type BESAPI struct {
	AdminField *struct {
		Resource string `xml:"Resource,attr"`
		Name     string `xml:"Name"`
		Value    string `xml:"Value"`
	} `xml:"AdminField"`
	Computer *struct {
		Resource string `xml:"Resource,attr"`
		Property []struct {
			Name     string `xml:"Name,attr"`
			CharData string `xml:",chardata"`
		} `xml:"Property"`
	} `xml:"Computer"`
	DashboardData *struct {
		Resource  string  `xml:"Resource,attr"`
		Dashboard string  `xml:"Dashboard"`
		IsPrivate bool    `xml:"IsPrivate"`
		Name      string  `xml:"Name"`
		User      *string `xml:"User"`
		Value     string  `xml:"Value"`
	} `xml:"DashboardData"`
	LDAPDirectory *struct {
		Resource          string `xml:"Resource,attr"`
		BaseDN            string `xml:"BaseDN"`
		GroupFilter       string `xml:"GroupFilter"`
		ID                int    `xml:"ID"`
		IsActiveDirectory bool   `xml:"IsActiveDirectory"`
		IsGlobalCatalog   bool   `xml:"IsGlobalCatalog"`
		Name              string `xml:"Name"`
		Servers           struct {
			Server struct {
				Host     string `xml:"Host"`
				Port     int    `xml:"Port"`
				Priority int    `xml:"Priority"`
			} `xml:"Server"`
		} `xml:"Servers"`
		UIDAttribute string `xml:"UIDAttribute"`
		UseSSL       bool   `xml:"UseSSL"`
		UserFilter   string `xml:"UserFilter"`
	} `xml:"LDAPDirectory"`
	ManualComputerGroup *struct {
		Resource         string `xml:"Resource,attr"`
		ComputerID       []int  `xml:"ComputerID"`
		EvaluateOnClient bool   `xml:"EvaluateOnClient"`
		Name             string `xml:"Name"`
	} `xml:"ManualComputerGroup"`
	MastheadParameters *struct {
		Resource                   string `xml:"Resource,attr"`
		ArchiveAllowUTF8           bool   `xml:"ArchiveAllowUTF8"`
		Controller                 string `xml:"Controller"`
		Enhanced91Security         bool   `xml:"Enhanced91Security"`
		GatherInterval             string `xml:"GatherInterval"`
		InitialLockState           string `xml:"InitialLockState"`
		PortNumber                 int    `xml:"PortNumber"`
		RequireFIPSCompliantCrypto bool   `xml:"RequireFIPSCompliantCrypto"`
		UseSHA256FileChecksOnly    bool   `xml:"UseSHA256FileChecksOnly"`
		UseSHA384SignaturesOnly    bool   `xml:"UseSHA384SignaturesOnly"`
	} `xml:"MastheadParameters"`
	Operator *struct {
		Resource                      string `xml:"Resource,attr"`
		ActionScriptCommandsPrivilege string `xml:"ActionScriptCommandsPrivilege"`
		CanCreateActions              bool   `xml:"CanCreateActions"`
		CanLock                       bool   `xml:"CanLock"`
		CanSendMultipleRefresh        bool   `xml:"CanSendMultipleRefresh"`
		CanSubmitQueries              bool   `xml:"CanSubmitQueries"`
		ComputerAssignments           struct {
			ByGroup struct {
				Name     string `xml:"Name,attr"`
				Resource string `xml:"Resource,attr"`
				Type     string `xml:"Type,attr"`
			} `xml:"ByGroup"`
		} `xml:"ComputerAssignments"`
		CustomContent   bool `xml:"CustomContent"`
		InterfaceLogins struct {
			API          bool `xml:"API"`
			Applications struct {
				Name []string `xml:"Name"`
			} `xml:"Applications"`
			Console bool `xml:"Console"`
			WebUI   bool `xml:"WebUI"`
		} `xml:"InterfaceLogins"`
		LDAPDN                      *string `xml:"LDAPDN"`
		LDAPServerID                *int    `xml:"LDAPServerID"`
		LastLoginTime               string  `xml:"LastLoginTime"`
		LoginPermission             string  `xml:"LoginPermission"`
		MasterOperator              bool    `xml:"MasterOperator"`
		Name                        string  `xml:"Name"`
		PostActionBehaviorPrivilege string  `xml:"PostActionBehaviorPrivilege"`
		ShowOtherActions            bool    `xml:"ShowOtherActions"`
		StopOtherActions            bool    `xml:"StopOtherActions"`
		UnmanagedAssetPrivilege     string  `xml:"UnmanagedAssetPrivilege"`
	} `xml:"Operator"`
	Role struct {
		Resource                      string `xml:"Resource,attr"`
		ActionScriptCommandsPrivilege string `xml:"ActionScriptCommandsPrivilege"`
		CanCreateActions              int    `xml:"CanCreateActions"`
		CanLock                       int    `xml:"CanLock"`
		CanSendMultipleRefresh        int    `xml:"CanSendMultipleRefresh"`
		CanSubmitQueries              int    `xml:"CanSubmitQueries"`
		ComputerAssignments           struct {
			AllComputers *struct{} `xml:"AllComputers"`
			ByGroup      struct {
				Name     string `xml:"Name,attr"`
				Resource string `xml:"Resource,attr"`
				Type     string `xml:"Type,attr"`
			} `xml:"ByGroup"`
		} `xml:"ComputerAssignments"`
		CustomContent   int `xml:"CustomContent"`
		ID              int `xml:"ID"`
		InterfaceLogins struct {
			API          bool `xml:"API"`
			Applications struct {
				Name []string `xml:"Name"`
			} `xml:"Applications"`
			Console bool `xml:"Console"`
			WebUI   bool `xml:"WebUI"`
		} `xml:"InterfaceLogins"`
		LDAPGroups struct {
			Group struct {
				DN       string `xml:"DN"`
				Name     string `xml:"Name"`
				ServerID int    `xml:"ServerID"`
			} `xml:"Group"`
		} `xml:"LDAPGroups"`
		MasterOperator int    `xml:"MasterOperator"`
		Name           string `xml:"Name"`
		Operators      struct {
			Explicit  *string  `xml:"Explicit"`
			Inherited []string `xml:"Inherited"`
		} `xml:"Operators"`
		PostActionBehaviorPrivilege string `xml:"PostActionBehaviorPrivilege"`
		ShowOtherActions            int    `xml:"ShowOtherActions"`
		Sites                       struct {
			CustomSite []struct {
				Name       string `xml:"Name"`
				Permission string `xml:"Permission"`
			} `xml:"CustomSite"`
			ExternalSite []struct {
				Name       string `xml:"Name"`
				Permission string `xml:"Permission"`
			} `xml:"ExternalSite"`
		} `xml:"Sites"`
		StopOtherActions        int    `xml:"StopOtherActions"`
		UnmanagedAssetPrivilege string `xml:"UnmanagedAssetPrivilege"`
	} `xml:"Role"`
	SystemOptions *struct {
		Resource                string `xml:"Resource,attr"`
		DefaultFixletVisibility string `xml:"DefaultFixletVisibility"`
		MinimumRefreshSeconds   int    `xml:"MinimumRefreshSeconds"`
	} `xml:"SystemOptions"`
}
