// This file is automatically generated. DO NOT EDIT.

package bfrest

type BESAPI struct {
	Action []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Action"`
	ActionSite struct {
		Resource    string `xml:"Resource,attr"`
		DisplayName string `xml:"DisplayName"`
		GatherURL   string `xml:"GatherURL"`
		Name        string `xml:"Name"`
	} `xml:"ActionSite"`
	Analysis []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Analysis"`
	Baseline *struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Baseline"`
	Computer []struct {
		Resource       string `xml:"Resource,attr"`
		ID             int    `xml:"ID"`
		LastReportTime string `xml:"LastReportTime"`
		Property       []struct {
			Name     string `xml:"Name,attr"`
			CharData string `xml:",chardata"`
		} `xml:"Property"`
	} `xml:"Computer"`
	ComputerGroup []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"ComputerGroup"`
	CustomSite []struct {
		Resource    string `xml:"Resource,attr"`
		DisplayName string `xml:"DisplayName"`
		GatherURL   string `xml:"GatherURL"`
		Name        string `xml:"Name"`
	} `xml:"CustomSite"`
	ExternalSite []struct {
		Resource    string   `xml:"Resource,attr"`
		DisplayName []string `xml:"DisplayName"`
		GatherURL   string   `xml:"GatherURL"`
		Name        string   `xml:"Name"`
	} `xml:"ExternalSite"`
	Fixlet []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Fixlet"`
	OperatorSite []struct {
		Resource    string `xml:"Resource,attr"`
		DisplayName string `xml:"DisplayName"`
		GatherURL   string `xml:"GatherURL"`
		Name        string `xml:"Name"`
	} `xml:"OperatorSite"`
	Task []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Task"`
}
