// This file is automatically generated. DO NOT EDIT.

package main

type BESAPI struct {
	Action []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Action"`
	ActionResults *struct {
		Resource string `xml:"Resource,attr"`
		ActionID int    `xml:"ActionID"`
		Computer []struct {
			ID         int     `xml:"ID,attr"`
			Name       string  `xml:"Name,attr"`
			ApplyCount int     `xml:"ApplyCount"`
			EndTime    *string `xml:"EndTime"`
			ExitCode   *int    `xml:"ExitCode"`
			LineNumber int     `xml:"LineNumber"`
			RetryCount int     `xml:"RetryCount"`
			StartTime  *string `xml:"StartTime"`
			State      struct {
				IsError  int    `xml:"IsError,attr"`
				CharData string `xml:",chardata"`
			} `xml:"State"`
			Status string `xml:"Status"`
		} `xml:"Computer"`
		DateIssued         string  `xml:"DateIssued"`
		DateStopped        *string `xml:"DateStopped"`
		MemberActionResult []struct {
			Resource string `xml:"Resource,attr"`
			ActionID int    `xml:"ActionID"`
			Computer []struct {
				ID         int    `xml:"ID,attr"`
				Name       string `xml:"Name,attr"`
				ApplyCount int    `xml:"ApplyCount"`
				EndTime    string `xml:"EndTime"`
				ExitCode   int    `xml:"ExitCode"`
				LineNumber int    `xml:"LineNumber"`
				RetryCount int    `xml:"RetryCount"`
				StartTime  string `xml:"StartTime"`
				State      struct {
					IsError  int    `xml:"IsError,attr"`
					CharData string `xml:",chardata"`
				} `xml:"State"`
				Status string `xml:"Status"`
			} `xml:"Computer"`
		} `xml:"MemberActionResult"`
		Status    string `xml:"Status"`
		StoppedBy *struct {
			UserID   int    `xml:"UserID,attr"`
			CharData string `xml:",chardata"`
		} `xml:"StoppedBy"`
	} `xml:"ActionResults"`
	ActionSite *struct {
		Resource    string `xml:"Resource,attr"`
		DisplayName string `xml:"DisplayName"`
		GatherURL   string `xml:"GatherURL"`
		Name        string `xml:"Name"`
	} `xml:"ActionSite"`
	AdminField []struct {
		Resource string `xml:"Resource,attr"`
		Name     string `xml:"Name"`
		Value    string `xml:"Value"`
	} `xml:"AdminField"`
	Analysis []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Analysis"`
	Baseline []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Baseline"`
	Computer []struct {
		Resource       string `xml:"Resource,attr"`
		ID             int    `xml:"ID"`
		LastReportTime string `xml:"LastReportTime"`
	} `xml:"Computer"`
	ComputerGroup []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"ComputerGroup"`
	CustomSite []struct {
		Resource    string `xml:"Resource,attr"`
		DisplayName string `xml:"DisplayName"`
		GatherURL   string `xml:"GatherURL"`
		Name        string `xml:"Name"`
	} `xml:"CustomSite"`
	DashboardData []struct {
		Resource  string  `xml:"Resource,attr"`
		Dashboard string  `xml:"Dashboard"`
		IsPrivate bool    `xml:"IsPrivate"`
		Name      string  `xml:"Name"`
		User      *string `xml:"User"`
		Value     string  `xml:"Value"`
	} `xml:"DashboardData"`
	ExternalSite []struct {
		Resource    string   `xml:"Resource,attr"`
		DisplayName []string `xml:"DisplayName"`
		GatherURL   string   `xml:"GatherURL"`
		Name        string   `xml:"Name"`
	} `xml:"ExternalSite"`
	Fixlet []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Fixlet"`
	LDAPDirectory *struct {
		Resource          string `xml:"Resource,attr"`
		BaseDN            string `xml:"BaseDN"`
		GroupFilter       string `xml:"GroupFilter"`
		ID                int    `xml:"ID"`
		IsActiveDirectory bool   `xml:"IsActiveDirectory"`
		IsGlobalCatalog   bool   `xml:"IsGlobalCatalog"`
		Name              string `xml:"Name"`
		Servers           struct {
			Server struct {
				Host     string `xml:"Host"`
				Port     int    `xml:"Port"`
				Priority int    `xml:"Priority"`
			} `xml:"Server"`
		} `xml:"Servers"`
		UIDAttribute string `xml:"UIDAttribute"`
		UseSSL       bool   `xml:"UseSSL"`
		UserFilter   string `xml:"UserFilter"`
	} `xml:"LDAPDirectory"`
	MastheadParameters *struct {
		Resource                   string `xml:"Resource,attr"`
		ArchiveAllowUTF8           bool   `xml:"ArchiveAllowUTF8"`
		Controller                 string `xml:"Controller"`
		Enhanced91Security         bool   `xml:"Enhanced91Security"`
		GatherInterval             string `xml:"GatherInterval"`
		InitialLockState           string `xml:"InitialLockState"`
		PortNumber                 int    `xml:"PortNumber"`
		RequireFIPSCompliantCrypto bool   `xml:"RequireFIPSCompliantCrypto"`
		UseSHA256FileChecksOnly    bool   `xml:"UseSHA256FileChecksOnly"`
		UseSHA384SignaturesOnly    bool   `xml:"UseSHA384SignaturesOnly"`
	} `xml:"MastheadParameters"`
	Operator []struct {
		Resource                      string `xml:"Resource,attr"`
		ActionScriptCommandsPrivilege string `xml:"ActionScriptCommandsPrivilege"`
		CanCreateActions              bool   `xml:"CanCreateActions"`
		CanLock                       bool   `xml:"CanLock"`
		CanSendMultipleRefresh        bool   `xml:"CanSendMultipleRefresh"`
		CanSubmitQueries              bool   `xml:"CanSubmitQueries"`
		CustomContent                 bool   `xml:"CustomContent"`
		InterfaceLogins               struct {
			API          bool `xml:"API"`
			Applications struct {
				Name []string `xml:"Name"`
			} `xml:"Applications"`
			Console bool `xml:"Console"`
			WebUI   bool `xml:"WebUI"`
		} `xml:"InterfaceLogins"`
		LDAPDN                      *string `xml:"LDAPDN"`
		LDAPServerID                *int    `xml:"LDAPServerID"`
		LastLoginTime               string  `xml:"LastLoginTime"`
		LoginPermission             string  `xml:"LoginPermission"`
		MasterOperator              bool    `xml:"MasterOperator"`
		Name                        string  `xml:"Name"`
		PostActionBehaviorPrivilege string  `xml:"PostActionBehaviorPrivilege"`
		ShowOtherActions            bool    `xml:"ShowOtherActions"`
		StopOtherActions            bool    `xml:"StopOtherActions"`
		UnmanagedAssetPrivilege     string  `xml:"UnmanagedAssetPrivilege"`
	} `xml:"Operator"`
	OperatorSite []struct {
		Resource    string `xml:"Resource,attr"`
		DisplayName string `xml:"DisplayName"`
		GatherURL   string `xml:"GatherURL"`
		Name        string `xml:"Name"`
	} `xml:"OperatorSite"`
	Property []struct {
		Resource   string `xml:"Resource,attr"`
		ID         int    `xml:"ID"`
		IsReserved int    `xml:"IsReserved"`
		Name       string `xml:"Name"`
	} `xml:"Property"`
	Role []struct {
		Resource                      string `xml:"Resource,attr"`
		ActionScriptCommandsPrivilege string `xml:"ActionScriptCommandsPrivilege"`
		CanCreateActions              int    `xml:"CanCreateActions"`
		CanLock                       int    `xml:"CanLock"`
		CanSendMultipleRefresh        int    `xml:"CanSendMultipleRefresh"`
		CanSubmitQueries              int    `xml:"CanSubmitQueries"`
		ComputerAssignments           struct {
			AllComputers *struct{} `xml:"AllComputers"`
			ByGroup      struct {
				Name     string `xml:"Name,attr"`
				Resource string `xml:"Resource,attr"`
				Type     string `xml:"Type,attr"`
			} `xml:"ByGroup"`
		} `xml:"ComputerAssignments"`
		CustomContent   int `xml:"CustomContent"`
		ID              int `xml:"ID"`
		InterfaceLogins struct {
			API          bool `xml:"API"`
			Applications struct {
				Name []string `xml:"Name"`
			} `xml:"Applications"`
			Console bool `xml:"Console"`
			WebUI   bool `xml:"WebUI"`
		} `xml:"InterfaceLogins"`
		LDAPGroups struct {
			Group struct {
				DN       string `xml:"DN"`
				Name     string `xml:"Name"`
				ServerID int    `xml:"ServerID"`
			} `xml:"Group"`
		} `xml:"LDAPGroups"`
		MasterOperator int    `xml:"MasterOperator"`
		Name           string `xml:"Name"`
		Operators      struct {
			Explicit  *string  `xml:"Explicit"`
			Inherited []string `xml:"Inherited"`
		} `xml:"Operators"`
		PostActionBehaviorPrivilege string `xml:"PostActionBehaviorPrivilege"`
		ShowOtherActions            int    `xml:"ShowOtherActions"`
		Sites                       struct {
			CustomSite []struct {
				Name       string `xml:"Name"`
				Permission string `xml:"Permission"`
			} `xml:"CustomSite"`
			ExternalSite []struct {
				Name       string `xml:"Name"`
				Permission string `xml:"Permission"`
			} `xml:"ExternalSite"`
		} `xml:"Sites"`
		StopOtherActions        int    `xml:"StopOtherActions"`
		UnmanagedAssetPrivilege string `xml:"UnmanagedAssetPrivilege"`
	} `xml:"Role"`
	SystemOptions *struct {
		Resource                string `xml:"Resource,attr"`
		DefaultFixletVisibility string `xml:"DefaultFixletVisibility"`
		MinimumRefreshSeconds   int    `xml:"MinimumRefreshSeconds"`
	} `xml:"SystemOptions"`
	Task []struct {
		LastModified string `xml:"LastModified,attr"`
		Resource     string `xml:"Resource,attr"`
		ID           int    `xml:"ID"`
		Name         string `xml:"Name"`
	} `xml:"Task"`
	WebReports struct {
		URL string `xml:"URL"`
	} `xml:"WebReports"`
}
