// This file is automatically generated. DO NOT EDIT.

package bfrest

type BESAPI struct {
	Computer []struct {
		Resource       string `xml:"Resource,attr"`
		ID             int    `xml:"ID"`
		LastReportTime string `xml:"LastReportTime"`
	} `xml:"Computer"`
}
