// This file is automatically generated. DO NOT EDIT.

package bfrest

type BESAPI struct {
	Computer struct {
		Resource string `xml:"Resource,attr"`
		Property []struct {
			Name     string `xml:"Name,attr"`
			CharData string `xml:",chardata"`
		} `xml:"Property"`
	} `xml:"Computer"`
}
